import { basename, dirname } from "node:path";
import * as vscode from "vscode";
import type { KtcRenameResultViewModel, KtcRenameResultRowViewModel } from "../../../src/renameResultViewModel.js";
import { ktcActivateResultAccordion, ktcRegisterResultAccordion } from "./resultAccordion.js";
type Node = { type: "group"; rows: readonly KtcRenameResultRowViewModel[] } | { type: "file"; row: KtcRenameResultRowViewModel };
const VIEW_ID = "ktAutoCode.codeRenameResults";
export class KtcCodeRenameResultView implements vscode.TreeDataProvider<Node>, vscode.Disposable {
  private readonly emitter = new vscode.EventEmitter<Node | undefined>(); private readonly tree: vscode.TreeView<Node>; private model: KtcRenameResultViewModel | undefined; private expanded = true; private open?: (row: KtcRenameResultRowViewModel) => Promise<void>;
  readonly onDidChangeTreeData = this.emitter.event;
  constructor(context: vscode.ExtensionContext) { this.tree = vscode.window.createTreeView(VIEW_ID, { treeDataProvider: this, showCollapseAll: true }); context.subscriptions.push(this.tree, ktcRegisterResultAccordion(VIEW_ID, this), vscode.commands.registerCommand("ktAutoCode.codeRenameResult.open", (n: Node) => { if (n?.type === "file") void this.open?.(n.row); }), vscode.commands.registerCommand("ktAutoCode.codeRenameResult.close", () => void this.close()), vscode.commands.registerCommand("ktAutoCode.codeRenameResult.show", () => void this.showCached()), this.tree.onDidExpandElement(({ element }) => { if (element.type === "group") { this.expanded = true; ktcActivateResultAccordion(VIEW_ID); } }), this.tree.onDidCollapseElement(({ element }) => { if (element.type === "group") this.expanded = false; })); }
  show(model: KtcRenameResultViewModel, open: (row: KtcRenameResultRowViewModel) => Promise<void>): void { this.model = model; this.open = open; this.expanded = true; this.emitter.fire(undefined); void this.activate(); }
  getTreeItem(n: Node): vscode.TreeItem { if (n.type === "group") { const i = new vscode.TreeItem(`${this.model?.applied ? "已替换" : "预览"} · ${n.rows.length} 项`, this.expanded ? vscode.TreeItemCollapsibleState.Expanded : vscode.TreeItemCollapsibleState.Collapsed); i.iconPath = new vscode.ThemeIcon(this.model?.applied ? "check" : "search"); i.contextValue = "ktAutoCode.codeRename.group"; i.description = this.model ? `${this.model.summary.replacements} 处替换 · ${this.model.summary.errors} 错误` : ""; return i; } const r = n.row; const i = new vscode.TreeItem(r.sourceName || basename(r.originalFullPath), vscode.TreeItemCollapsibleState.None); i.resourceUri = vscode.Uri.file(r.openPath); i.description = [dirname(r.originalFullPath).replace(/^\.$/, ""), `${r.occurrences} 处`, r.targetOrPositionLabel, r.statusLabel].filter(Boolean).join(" · "); i.tooltip = `${r.originalFullPath}\n${r.targetOrPositionLabel}\n${r.detail ?? r.statusLabel}`; i.contextValue = "ktAutoCode.codeRename.file"; i.command = { command: "ktAutoCode.codeRenameResult.open", title: "打开文件", arguments: [n] }; return i; }
  getChildren(n?: Node): Node[] { if (n?.type === "group") return n.rows.map((row) => ({ type: "file", row })); return n ? [] : this.model?.rows.length ? [{ type: "group", rows: this.model.rows }] : []; } getParent(n: Node): Node | undefined { return n.type === "file" && this.model ? { type: "group", rows: this.model.rows } : undefined; } collapseForAccordion(): void { if (this.expanded) { this.expanded = false; this.emitter.fire(undefined); } } dispose(): void { this.emitter.dispose(); }
  private async close(): Promise<void> { await vscode.commands.executeCommand("setContext", "ktAutoCode.codeRenameHasResults", false); } private async showCached(): Promise<void> { if (this.model) { this.expanded = true; await this.activate(); } } private async activate(): Promise<void> { ktcActivateResultAccordion(VIEW_ID); await vscode.commands.executeCommand("setContext", "ktAutoCode.codeRenameHasResults", true); await vscode.commands.executeCommand("workbench.view.extension.kt-auto-code"); const g = this.getChildren()[0]; if (g?.type === "group") await this.tree.reveal(g, { select: false, focus: true, expand: true }); }
}
